function EN() {
    openChoiseLanguage()
    document.getElementById('fries').innerHTML = 'French fries';
    document.getElementById('salads').innerHTML = 'Salads'
    document.getElementById('mex0').innerHTML = 'Three soft corn tortillas filled with marinated beef, pineapple, cilantro and onions. Served with a lime wedge.'
    document.getElementById('mex1').innerHTML = 'Corn tortillas filled with chicken covered in green tomato sauce and cheese. Served with rice and beans.'
    document.getElementById('mex2').innerHTML = 'Freshly prepared from ripe avocados, lime juice, onions, tomatoes and coriander. Served with crispy tortilla chips.'
    document.getElementById('pizza0').innerHTML = 'Classic pizza with fresh tomatoes, mozzarella and basil.'
    document.getElementById('pizza1').innerHTML = 'Pizza topped with spicy pepperoni slices and mozzarella.'
    document.getElementById('pizza2').innerHTML = 'Fresh selection of vegetables such as peppers, onions, mushrooms and olives on a tomato sauce and mozzarella.'
    document.getElementById('burger0').innerHTML = 'Juicy beef patty with melted cheddar cheese, lettuce, tomato, onion and cucumber. Served in a brioche bun.'
    document.getElementById('burger1').innerHTML = 'Beef patty with BBQ sauce, crispy bacon, cheddar cheese and fried onions. Served in a brioche bun.'
    document.getElementById('burger2').innerHTML = 'Homemade vegetable patty with lettuce, tomato, avocado and a creamy yogurt sauce. Served in a wholemeal bun.'
    document.getElementById('fries0').innerHTML = 'Crispy fried potato sticks, seasoned with salt.'
    document.getElementById('fries1').innerHTML = 'Crispy fried sweet potato sticks, lightly salted.'
    document.getElementById('fries2').innerHTML = 'French fries covered in chili con carne and melted cheddar cheese.'
    document.getElementById('salad0').innerHTML = 'Fresh romaine lettuce with Caesar dressing, croutons and parmesan. With chicken if desired'
    document.getElementById('salad1').innerHTML = 'Fresh tomatoes, cucumbers, red onions, olives and feta cheese, garnished with oregano and olive oil.'
    document.getElementById('salad2').innerHTML = 'Nutrient-rich quinoa mixed with chickpeas, avocado, tomatoes and a light lemon dressing.'
    document.getElementById('dessert0').innerHTML = 'Deep fried dough sticks sprinkled with cinnamon and sugar, served with a rich chocolate sauce.'
    document.getElementById('dessert1').innerHTML = 'Classic cheesecake on a crispy biscuit base, served with strawberry sauce.'
    document.getElementById('dessert2').innerHTML = 'Warm chocolate brownie served with a scoop of vanilla ice cream and chocolate sauce.'
    document.getElementById('ShoppingBasket').innerHTML = 'Shopping Basket'
    document.getElementById('deliverText').innerHTML = 'Delivery'
    document.getElementById('mobileShoppingBasket').innerHTML = 'Shopping basket'
    document.getElementById('pickUpText').innerHTML = 'Pick up'
    document.getElementById('basketinfo1').innerHTML = 'Fill your shopping cart'
    document.getElementById('basketinfo2').innerHTML = 'Add some delicious dishes from the Add the menu and order your food.'
    document.getElementById('dataProtection').innerHTML = 'Data protection'
    document.getElementById('imprint').innerHTML = 'Imprint'
    document.getElementById('Pommes').innerHTML = 'French fries'
    document.getElementById('Salate').innerHTML = 'Salads'
    document.getElementById('subtotal').innerHTML = 'Subtotal'
    document.getElementById('deliveryCosts').innerHTML = 'Delivery costs'
    document.getElementById('total').innerHTML = 'Total cost'
}

function DE() {
    openChoiseLanguage()
    document.getElementById('fries').innerHTML = 'Pommes'
    document.getElementById('salads').innerHTML = 'Salate'
    document.getElementById('mex0').innerHTML = 'Drei weiche Maistortillas gefüllt mit mariniertem Rindfleisch, Ananas, Koriander und Zwiebeln. Serviert mit einer Limettenspalte.'
    document.getElementById('mex1').innerHTML = 'Mais-Tortillas gefüllt mit Hühnchen, überzogen mit grüner Tomatensauce und Käse. Serviert mit Reis und Bohnen.'
    document.getElementById('mex2').innerHTML = 'Frisch zubereitet aus reifen Avocados, Limettensaft, Zwiebeln, Tomaten und Koriander. Serviert mit knusprigen Tortilla-Chips.'
    document.getElementById('pizza0').innerHTML = 'Klassische Pizza mit frischen Tomaten, Mozzarella und Basilikum.'
    document.getElementById('pizza1').innerHTML = 'Pizza belegt mit würzigen Pepperoni-Scheiben und Mozzarella.'
    document.getElementById('pizza2').innerHTML = 'Frische Gemüseauswahl wie Paprika, Zwiebeln, Pilze und Oliven auf einer Tomatensauce und Mozzarella.'
    document.getElementById('burger0').innerHTML = 'Saftiges Rindfleisch-Patty mit geschmolzenem Cheddar-Käse, Salat, Tomate, Zwiebel und Gurke. Serviert im Brioche-Brötchen.'
    document.getElementById('burger1').innerHTML = 'Rindfleisch-Patty mit BBQ-Sauce, knusprigem Speck, Cheddar-Käse und Röstzwiebeln. Serviert im Brioche-Brötchen.'
    document.getElementById('burger2').innerHTML = 'Hausgemachtes Gemüse-Patty mit Salat, Tomate, Avocado und einer cremigen Joghurt-Sauce. Serviert im Vollkorn-Brötchen.'
    document.getElementById('fries0').innerHTML = 'Knusprig frittierte Kartoffelstäbchen, gewürzt mit Salz.'
    document.getElementById('fries1').innerHTML = 'Knusprig frittierte Süßkartoffelstäbchen, leicht gesalzen.'
    document.getElementById('fries2').innerHTML = 'Pommes frites überzogen mit Chili con Carne und geschmolzenem Cheddar-Käse.'
    document.getElementById('salad0').innerHTML = 'Frischer Römersalat mit Caesar-Dressing, Croutons und Parmesan. Auf Wunsch mit Hähnchen'
    document.getElementById('salad1').innerHTML = 'Frische Tomaten, Gurken, rote Zwiebeln, Oliven und Feta-Käse, garniert mit Oregano und Olivenöl.'
    document.getElementById('salad2').innerHTML = 'Nährstoffreicher Quinoa gemischt mit Kichererbsen, Avocado, Tomaten und einem leichten Zitronendressing.'
    document.getElementById('dessert0').innerHTML = 'Frittierte Teigstangen, bestreut mit Zimt und Zucker, serviert mit einer reichhaltigen Schokoladensauce.'
    document.getElementById('dessert1').innerHTML = 'Klassischer Käsekuchen auf einem knusprigen Keksboden, serviert mit Erdbeersauce.'
    document.getElementById('dessert2').innerHTML = 'Warmer Schokoladenbrownie, serviert mit einer Kugel Vanilleeis und Schokoladensauce.'
    document.getElementById('ShoppingBasket').innerHTML = 'Warenkorb'
    document.getElementById('deliverText').innerHTML = 'Lieferung'
    document.getElementById('mobileShoppingBasket').innerHTML = 'Warenkorb'
    document.getElementById('pickUpText').innerHTML = 'Abholung'
    document.getElementById('basketinfo1').innerHTML = 'Fülle deinen Warenkorb'
    document.getElementById('basketinfo2').innerHTML = 'Füge einige leckere Gerichte aus der Speisekarte hinzu und bestelle dein Essen.'
    document.getElementById('dataProtection').innerHTML = 'Datenschutzerklärung'
    document.getElementById('imprint').innerHTML = 'Impressum'
    document.getElementById('Pommes').innerHTML = 'Pommes'
    document.getElementById('Salate').innerHTML = 'Salate'
    document.getElementById('subtotal').innerHTML = 'Zwischensumme'
    document.getElementById('deliveryCosts').innerHTML = 'Lieferkosten'
    document.getElementById('total').innerHTML = 'Gesamt'
}